# Deploy to release branch
#
# Docs: https://github.com/aenetworks/aetn.samples.release/blob/master/docs/app-workflow.md#deploy-prod
---
name: Deploy Prod

on:
  release:
    types:
      - released

jobs:
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - uses: aenetworks/actions/deploy-prod@release
