# Preview changelog
#
# Docs: https://github.com/aenetworks/aetn.samples.release/blob/master/docs/app-workflow.md#preview-changelog
---
name: Preview changelog

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NPM_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}

jobs:
  preview-changelog:
    name: Preview changelog
    runs-on: ubuntu-latest
    steps:
      - uses: aenetworks/actions/preview-changelog@release
