# Run linters and unit tests
#
# Docs: https://github.com/aenetworks/aetn.samples.release/blob/master/docs/app-workflow.md#test--lint
---
name: Test & Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request_target:

env:
  NPM_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: aenetworks/actions/unit-tests@release
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: aenetworks/actions/linters@release
