name: 'Deploy QA'
description: 'Move code from develop to master branch which triggers deploy QA environment.'
inputs:
  apiKey:
    description: ''
    required: true
  collectionId:
    description: ''
    required: true
  environmentId:
    description: ''
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/postman.js']
