name: 'Clone'
description: 'test'
inputs:
  ref:
    description: 'Ref'
    default: ${{ github.event.pull_request.head.sha || github.ref }}
    required: false
  token:
    description: 'Token'
    default: ${{ github.token }}
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/scraps/clone-repository.js']

