name: 'Script runner'
description: 'Setup repository, install dependencies and run script'
inputs:
  script:
    description: 'NPM script to execute'
    required: true
  ref:
    description: 'Ref'
    default: ${{ github.event.pull_request.head.sha || github.ref }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token'
    required: false
  botUsername:
    description: 'username'
    default: 'Github Actions Bot'
    required: false
  botEmail:
    description: 'emails'
    required: false
runs:
  using: 'docker'
  image: '../Dockerfile'
  args: ['node', '/action/lib/actions/script-runner-action.js']

