name: 'Script runner'
description: 'Setup repository, install dependencies and run script'
inputs:
  script:
    description: 'NPM script to execute'
    required: true
  ref:
    description: 'Ref'
    default: ${{ github.event.pull_request.head.sha || github.ref }}
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ github.token }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  botUsername:
    description: 'GitHub bot username or env variable BOT_NAME'
    default: 'GitHub Actions Bot'
    required: false
  botEmail:
    description: 'Github bot email or env variable BOT_EMAIL'
    required: false
runs:
  using: 'docker'
  image: '../Dockerfile'
  args: ['node', '/action/lib/actions/script-runner-action.js']

