name: 'Setup registry'
description: 'test'
author: 'Pawel Drozd'
inputs:
  npmAuthToken:
    description: 'auth token'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:latest'
  args: ['node', '/action/dist/scraps/setup-registry.js']

