name: 'Deploy QA'
description: 'Move code from develop to master branch which triggers deploy QA environment.'
inputs:
  sourceRef:
    description: 'From which branch it should be deployed.'
    default: 'develop'
    required: false
  targetRef:
    description: 'To which branch it should be deployed.'
    default: 'master'
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ github.token }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  force:
    description: 'Use force strategy to push [true/false*]'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/deploy-qa.js']
