name: 'Deploy QA'
description: 'Move code from develop to master branch which triggers deploy QA environment.'
inputs:
  sourceRef:
    description: 'From which branch it should be deployed.'
    default: 'develop'
    required: false
  targetRef:
    description: 'To which branch it should be deployed.'
    default: 'master'
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ secrets.GPR_AUTH_TOKEN }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  force:
    description: 'Use force strategy to push [true/false*]'
    required: false
    default: 'false'
  botUsername:
    description: 'GitHub bot username or env variable GH_ACTION_BOT_NAME'
    default: 'aetn'
    required: false
  botEmail:
    description: 'Github bot email or env variable GH_ACTION_BOT_EMAIL'
    default: ${{ secrets.GH_ACTION_BOT_EMAIL }}
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/deploy-qa.js']
