name: 'Deploy Prod'
description: 'Move code from last tag to release branch which triggers deploy Prod environment.'
inputs:
  targetRef:
    description: 'To which branch it should be deployed.'
    default: 'master'
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ github.token }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  force:
    description: "Use this option if history of your branches isn't linear and you want to fix it. It will force push sourceRef to targetRef! [true/false]"
    default: 'false'
    required: false
runs:
  using: 'docker'
  image: '../Dockerfile'
  args: ['node', '/action/lib/deploy-prod.js']
