name: 'Run script'
description: 'test'
author: 'Pawel Drozd'
inputs:
  script:
    description: 'Script'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/scraps/run-npm-script.js']

