name: 'Search new docker image tags'
description: 'Create new PRs if there is any new base docker image'
inputs:
  ref:
    description: 'Ref'
    default: ${{ github.event.pull_request.head.sha || github.ref }}
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ github.token }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  botUsername:
    description: 'GitHub bot username or env variable GH_ACTION_BOT_NAME'
    default: 'GitHub Actions Bot'
    required: false
  botEmail:
    description: 'Github bot email or env variable GH_ACTION_BOT_EMAIL'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/search-new-docker-images.js']
