name: 'Unit Tests'
description: 'Run unit tests'
inputs:
  ref:
    description: 'Ref'
    default: ${{ github.event.pull_request.head.sha || github.ref }}
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ github.token }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  timeout:
    description: 'Action run timeout.'
    default: 10m
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/unit-tests.js']

