name: 'Publish release package'
description: 'Publish npm package to registry from last release'
inputs:
  ref:
    description: 'Ref'
    default: ${{ github.event.pull_request.head.sha || github.ref }}
    required: false
  token:
    description: 'GitHub Token'
    default: ${{ github.token }}
    required: false
  npmAuthToken:
    description: 'NPM Auth Token or env variable NPM_AUTH_TOKEN'
    required: false
  isPrerelease:
    description: ''
    default: ${{ github.event.release.prerelease }}
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/aenetworks/actions:test'
  args: ['node', '/action/dist/publish-package.js']
