# Deploy to release branch
#
# Docs: https://github.com/aenetworks/aetn.samples.release/blob/master/docs/app-workflow.md#deploy-prod
---
name: Deploy Prod

on:
  release:
    types:
      - released

jobs:
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - uses: aenetworks/actions/deploy-prod@release

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs:
      - deploy-prod
    steps:
      - uses: aenetworks/actions/scraps/clone-repository@release
        with:
          ref: 'release'
      - uses: aenetworks/actions/scraps/setup-registry@release
        with:
          npmAuthToken: ${{ secrets.GPR_AUTH_TOKEN }}
      - uses: aenetworks/actions/scraps/install-dependencies@release
      - uses: aenetworks/actions/scraps/run-npm-script@release
        with:
          script: build
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GPR_AUTH_TOKEN }}
      - name: Build docker image
        run: |
          docker build -t ghcr.io/aenetworks/actions:latest .
          docker push ghcr.io/aenetworks/actions:latest

